config/routes.rb
Rails.application.routes.draw do
  resources :vacants
  devise_for :people
  devise_for :companies
  #get 'sites/index'
  root to: "vacants#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :vacants, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/modality.rb
class Modality < ApplicationRecord
  has_many :vacants
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :postulations
  has_many :vacants, through: :postulations

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/postulation.rb
class Postulation < ApplicationRecord
  belongs_to :person
  belongs_to :vacant
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :vacants

end

app/models/vacant.rb
class Vacant < ApplicationRecord
  belongs_to :company
  belongs_to :region
  belongs_to :modality
  has_many :people
  has_many :people, through: :postulations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vacants_controller.rb
class VacantsController < ApplicationController
  before_action :set_vacant, only: %i[ show edit update destroy ]

  # GET /vacants or /vacants.json
  def index
    @vacants = Vacant.all
  end

  # GET /vacants/1 or /vacants/1.json
  def show
  end

  # GET /vacants/new
  def new
    @vacant = Vacant.new
  end

  # GET /vacants/1/edit
  def edit
  end

  # POST /vacants or /vacants.json
  def create
    @vacant = current_company.vacants.new(vacant_params)
    @vacant.modality = Modality.find(params[:vacant][:modality_id])
    @vacant.region = Region.find(params[:vacant][:region_id])
    respond_to do |format|
      if @vacant.save
        format.html { redirect_to vacant_url(@vacant), notice: "Vacant was successfully created." }
        format.json { render :show, status: :created, location: @vacant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vacant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacants/1 or /vacants/1.json
  def update
    respond_to do |format|
      if @vacant.update(vacant_params)
        format.html { redirect_to vacant_url(@vacant), notice: "Vacant was successfully updated." }
        format.json { render :show, status: :ok, location: @vacant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vacant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacants/1 or /vacants/1.json
  def destroy
    @vacant.destroy

    respond_to do |format|
      format.html { redirect_to vacants_url, notice: "Vacant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def author
    @vacant = Vacant.find(params[:company_id])

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacant
      @vacant = Vacant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vacant_params
      params.require(:vacant).permit(
        :job,
        :description,
        :number_vacancies,
        :start_salary,
        :end_salary,
        :start_date,
        :company_id,
        :region_id,
        :modality_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/vacants_helper.rb
module VacantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Empleos para Desarrolladores Web</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <%end%>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <%end%>

    <%= render 'partials/nav' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
   <%= link_to "Inicio", root_path, class: "nav-link active" %>
  </li>
  <% if company_signed_in? || person_signed_in?%>
        <% if company_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Cerrar Sesión', destroy_company_session_path, method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Publicar Aviso', new_vacant_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Mis avisos</a>
        </li>
      <%end%>
      <% if person_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Cerrar Sesión', destroy_person_session_path, method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Mis postulaciones</a>
          </li>
      <%end%>
    <%else%>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">Iniciar Sesión ó Registrarse</a>
        <div class="dropdown-menu">
          <%= link_to 'Soy Empresa', new_company_session_path, class:"dropdown-item" %>
          <%= link_to 'Soy Desarrollador', new_person_session_path, class:"dropdown-item" %>
      </li>
  <%end%>
</ul>

app/views/vacants/_form.html.erb
<%= form_with(model: vacant) do |form| %>
  <% if vacant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vacant.errors.count, "error") %> prohibited this vacant from being saved:</h2>

      <ul>
        <% vacant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :job, "Cargo" %>
    <br>
    <%= form.text_field :job %>
  </div>

  <div class="field">
    <%= form.label :description, "Descripción del Puesto" %>
    <br>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :number_vacancies, "Cantidad de Vacantes" %>
    <br>
    <%= form.number_field :number_vacancies %>
  </div>

  <div class="field">
    <%= form.label :start_salary, "Salario Mínimo del Cargo" %>
    <br>
    <%= form.number_field :start_salary %>
  </div>

  <div class="field">
    <%= form.label :end_salary, "Salario Máximo del Cargo" %>
    <br>
    <%= form.number_field :end_salary %>
  </div>

  <div class="field">
    <%= form.label :start_date, "Fecha de Inicio del Trabajo" %>
    <br>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <p>Región en la que se Desarrollará el Trabajo</p>
    <%= collection_select(:vacant, :region_id, Region.all, :id, :name, prompt: true) %>
  </div>

  <div class="field">
    <p>Modalidad de Trabajo</p>
    <%= collection_select(:vacant, :modality_id, Modality.all, :id, :name, prompt: true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vacants/edit.html.erb
<div class="small-container center-block" >

  <h1>Editar Oferta</h1>

  <%= render 'form', vacant: @vacant %>

  <%= link_to 'Show', @vacant %> |
  <%= link_to 'Back', vacants_path %>

</div>

app/views/vacants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vacantes Disponibles</h1>
<table>
  <thead>
    <tr>
      <th>Cargo</th>
      <th>Descripción</th>
      <th>Start salary</th>
      <th>End salary</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @vacants.order('created_at DESC').each do |vacant| %>
      <tr>
        <td><h3 class="text-uppercase"><%= vacant.job %></h3></td>
        <td><%= vacant.description %></td>
        <td>$<%= number_with_delimiter(vacant.start_salary) %></td>
        <td>$<%= number_with_delimiter(vacant.end_salary) %></td>
        <td><%= link_to 'Más Detalles', vacant %></td>
        <% if company_signed_in? %>
         <td><%= link_to 'Destroy', vacant, method: :delete, data: { confirm: 'Are you sure?' } %><td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/vacants/new.html.erb
<div class="small-container center-block" >

 <h1>Nuevo Aviso</h1>

 <%= render 'form', vacant: @vacant %>

 <%= link_to 'Ir a Inicio', vacants_path %>

</div>

app/views/vacants/show.html.erb
<div class="small-container center-block" >

<p>
  <strong>Cargo:</strong>
  <%= @vacant.job %>
</p>

<p>
  <strong>Descripción del Puesto:</strong>
  <%= @vacant.description %>
</p>

<p>
  <strong>Cantidad de Vacantes:</strong>
  <%= @vacant.number_vacancies %>
</p>

<p>
  <strong>Salario Mínimo del Cargo:</strong>
  $ <%= number_with_delimiter(@vacant.start_salary) %>
</p>

<p>
  <strong>Salario Máximo del Cargo:</strong>
  $ <%= number_with_delimiter(@vacant.end_salary) %>
</p>

<p>
  <strong>Fecha de Inicio del Trabajo:</strong>
  <%= @vacant.start_date %>
</p>

<p>
  <strong>id_empresa:</strong>
  <%= @vacant.company_id %>
</p>

<p>
  <strong>Región en la que se Desarrollará el Trabajo:</strong>
  <%= @vacant.region.name %>
</p>

<p>
  <strong>Modalidad de Trabajo:</strong>
  <%= @vacant.modality.name %>
</p>

<p id="notice"><%= notice %></p>
<%if company_signed_in? %>
  <%= link_to 'Editar', edit_vacant_path(@vacant) %>
<%end%>|
<%= link_to 'Ir al Inicio', vacants_path %>

</div>